version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8182:8080"
    volumes:
      - .:/app
    command: php artisan serve --host=0.0.0.0 --port=8080
    # environment:
    #   - APP_ENV=local
    #   - APP_DEBUG=true
    #   - APP_KEY=${APP_KEY}
    #   - CACHE_DRIVER=file
    #   - QUEUE_CONNECTION=sync
    #   - REDIS_HOST=redis
    #   - DB_CONNECTION=mysql
    #   - DB_HOST=db
    #   - DB_PORT=3306
    #   - DB_DATABASE=blog-api
    #   - DB_USERNAME=root
    #   - DB_PASSWORD=root_password

volumes:
  dbdata:
